- src/main/java/net/syscon/elite/api/model/PrisonToCourtEvent.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
Identified need for additional optional 'comments' field after a conversation with the PECS team.
Also added validation constraints to the model object.
> Added optional comments field to model object and fleshed out its constraints.

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/EventStatus.java
- src/main/java/net/syscon/elite/repository/jpa/model/EventType.java
- src/main/java/net/syscon/elite/repository/jpa/repository/CourtEventRepository.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
So this is the initial entity that will be created as part of the PECS secure prison to court movements.  
The first stage will be to create a court event which is linked to a court case and offender booking.
> DT-576 initial JPA model to support creation of court events.

- src/main/java/net/syscon/elite/api/model/CourtCase.java
- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCourtCase.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderBookingRepositoryTest.java
Exposing court events entities (hearings) via court cases entity as this is ultimately what they are linked to.
> DT-584 pushing persistence and retrieval of court events entities into court cases entity.

- src/main/java/net/syscon/elite/repository/jpa/model/DisciplinaryAction.java
- src/main/java/net/syscon/elite/repository/jpa/model/MilitaryBranch.java
- src/main/java/net/syscon/elite/repository/jpa/model/MilitaryDischarge.java
- src/main/java/net/syscon/elite/repository/jpa/model/MilitaryRank.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderMilitaryRecord.java
- src/main/java/net/syscon/elite/repository/jpa/model/ReferenceCode.java
- src/main/java/net/syscon/elite/repository/jpa/model/WarZone.java
Not much to say other than small refactoring to reference codes on the back of other previous changes.
> DT-601 small refactorings to references codes.

- src/main/java/net/syscon/elite/repository/jpa/model/CaseStatus.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderBooking.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCourtCase.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/repository/jpa/model/OffenderBookingTest.java
- src/test/java/net/syscon/elite/repository/jpa/model/OffenderCourtCaseTest.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderBookingRepositoryTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Initial PR to add validation to the scheduling of court hearings.
> Dt 603 validation for court hearings

- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Small changes to the court hearings service to verify the date of the hearing i.e. in future and the (agency) court for the hearing is active.
> DT-603 changes to check court for hearing is currently active and hearing date is in future

- src/main/java/net/syscon/elite/web/config/JwkClient.java
This is a short term fix until we implement RemoteJwkSet.
> DT-609 Fix caching of JWK Set

- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/repository/jpa/model/CaseStatus.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest.java
- src/test/java/net/syscon/elite/repository/jpa/model/OffenderCourtCaseTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
- src/test/resources/net/syscon/elite/api/resource/impl/court_hearing.json
Removing stubbed API return value from endpoint and wiring in call to service layer to schedule (create) court hearings and return via API endpoint.
This also fixes a bug I found during testing with the case status being active.
> DT-604 initial commit to wire in actual court hearing creation into API endpoint.

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Court hearing comments were not being persisted for a court hearing (event).
> DT-604 fixing bug identified during end to end testing.

- src/main/java/net/syscon/elite/api/model/PrisonToCourtHearing.java
- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Change to re-purpose URL for court hearings.
> DT-604 changing URL to make it RESTful.

- src/main/java/net/syscon/elite/api/model/CourtHearing.java
- src/main/java/net/syscon/elite/api/model/CourtHearings.java
- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/main/java/net/syscon/elite/service/transformers/CourtCaseTransformer.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
- src/test/java/net/syscon/elite/service/transformers/CourtCaseTransformerTest.java
- src/test/resources/net/syscon/elite/api/resource/impl/court_cases.json
- src/test/resources/net/syscon/elite/api/resource/impl/court_hearing.json
Includes a few small tidy-ups in preparation for court hearings endpoint.
> DT-651 initial prep commit for new endpoint for court hearings.

- src/main/java/net/syscon/elite/api/model/CourtHearings.java
- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/repository/jpa/repository/CourtEventRepository.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
This still needs some filtering to be added though the number of hearings returned realistically will never be that much for a given booking.
> DT-651 wiring in call to concreate service method for retrieval of court hearings

- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/main/java/net/syscon/elite/service/LocationService.java
- src/main/java/net/syscon/elite/service/MovementUpdateService.java
- src/main/java/net/syscon/elite/service/support/ReferenceDomain.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementResourceApiTest_moveToCell.java
- src/test/java/net/syscon/elite/service/MovementUpdateServiceTest.java
Implements the moveToCell service, but still need to add the new repository updates.
> DT-235 Implement moveToCell service

- src/main/java/net/syscon/elite/api/resource/BookingResource.java
- src/main/java/net/syscon/elite/api/resource/impl/BookingResourceImpl.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/api/resource/impl/BookingResourceImplIntTest.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
- src/test/resources/net/syscon/elite/api/resource/impl/court_cases_active_and_inactive.json
Adding filter attribute to endpoint to allow inclusion of all court cases or only active active court cases.  Defaults to active only.
> DT-692 adding activeOnly filter flag for court cases associated with a booking.

- src/main/java/net/syscon/elite/repository/jpa/model/OffenderBooking.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/repository/jpa/model/OffenderBookingTest.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
Pushing filtering logic into the domain layer and also test tidy-ups.
> DT692 refactoring active court case by filtering pushing into the domain layer.

- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/repository/jpa/model/BedAssignmentHistory.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderBooking.java
- src/main/java/net/syscon/elite/repository/jpa/repository/BedAssignmentHistoriesRepository.java
- src/main/java/net/syscon/elite/service/BedAssignmentHistoryService.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/main/java/net/syscon/elite/service/LocationService.java
- src/main/java/net/syscon/elite/service/MovementUpdateService.java
- src/test/java/net/syscon/elite/repository/jpa/repository/BedAssignmentHistoriesRepositoryTest.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderBookingRepositoryTest.java
- src/test/java/net/syscon/elite/service/BedAssignmentHistoryServiceTest.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
- src/test/java/net/syscon/elite/service/MovementUpdateServiceTest.java
This is still WIP as there is more to do.  This PR can be merged into master as the endpoint still does nothing (yet).
> DT-235 Implement the write to Bed Assignment Histories

- src/main/java/net/syscon/elite/api/model/PrisonerDetail.java
- src/main/resources/sqls/InmateRepositoryImpl.sql
- src/test/resources/net/syscon/elite/api/resource/impl/prisoners_multiple.json
- src/test/resources/net/syscon/elite/api/resource/impl/prisoners_single.json
Add new fields `ethnicityCode` and `religionCode` to `/api/prisoners` and related resource responses. (`PrisonerDetail` class).
These primary key values are more stable than the description values used for `ethnicity` and `religion` and are easier to match. They will be used for new Use of Force reports - incidents by religious group and incidents by ethnic group. (DCS-198, DCS-199)
> DCS-198 Incidents by religion. DCS-199 Incidents by ethnic group.

- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Court hearings are not always linked to court cases.
There can be situations where there is no direct link back to the offenders court case(s).  For example the offender is going to court as a witness, ergo not related to their court case(s).
> DT-707 additional service method to support creation of court events not linked to a court case.

- src/main/java/net/syscon/elite/api/model/OffenderBooking.java
- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/repository/jpa/repository/AgencyInternalLocationRepository.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/main/java/net/syscon/elite/service/MovementUpdateService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementResourceApiTest_moveToCell.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_moveToCell.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
- src/test/java/net/syscon/elite/service/MovementUpdateServiceTest.java
Accept the new cell's code rather than its id.
> DT-235 movetocell bycode

- src/main/java/net/syscon/elite/api/model/PendingDeletionRequest.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/controller/DataComplianceController.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/dto/OffenderPendingDeletionEvent.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/dto/OffenderPendingDeletionReferralCompleteEvent.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/OffenderDeletionAwsEventPusher.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/OffenderDeletionNoOpEventPusher.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralService.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/controller/DataComplianceControllerTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/OffenderDeletionEventPusherTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/health/QueueHealthTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/repository/OffenderAliasPendingDeletionRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/repository/OffenderPendingDeletionRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralServiceTest.java
Updating Elite2 API side to match changes introduced [here](https://github.com/ministryofjustice/dps-data-compliance/pull/111)
> GDPR-50 Updating requestId -> batchId

- src/main/java/net/syscon/elite/api/model/CategorisationDetail.java
- src/main/java/net/syscon/elite/api/model/CategoryApprovalDetail.java
- src/main/java/net/syscon/elite/api/model/CategoryRejectionDetail.java
- src/main/java/net/syscon/elite/api/model/OffenderCategorise.java
- src/main/java/net/syscon/elite/api/resource/BookingResource.java
- src/main/java/net/syscon/elite/repository/impl/InmateRepositoryImpl.java
- src/main/java/net/syscon/elite/service/InmateService.java
- src/main/resources/sqls/InmateRepositoryImpl.sql
- src/test/java/net/syscon/elite/api/resource/impl/OffenderAssessmentResourceTest.java
- src/test/java/net/syscon/elite/executablespecification/steps/BookingAssessmentSteps.java
- src/test/java/net/syscon/elite/repository/InmateRepositoryTest.java
- src/test/java/net/syscon/elite/service/InmateServiceImplTest.java
- src/test/resources/features/booking_details.feature
Add extra fields that may be set by create / approve categorisation
> CAT-586 Add other categories to the cat-tool service

- src/main/java/net/syscon/elite/repository/jpa/model/EscortAgencyType.java
- src/main/java/net/syscon/elite/repository/jpa/model/MovementDirection.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderIndividualSchedule.java
- src/main/java/net/syscon/elite/repository/jpa/repository/OffenderIndividualScheduleRepository.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderIndividualScheduleRepositoryTest.java
This forms the initial JPA entities to support scheduling of prison to prison moves.
> DT-782 inital commit for JPA entity Offender Individual Schedule.

- build.gradle
- src/main/java/net/syscon/elite/api/model/PrisonToPrisonMove.java
- src/main/java/net/syscon/elite/api/model/ScheduledPrisonToPrisonMove.java
- src/main/java/net/syscon/elite/service/PrisonToPrisonMoveSchedulingService.java
- src/test/java/net/syscon/elite/service/PrisonToPrisonMoveSchedulingServiceTest.java
Added new modal return type for service layer to populate and return for prison to prison moves.
Also reverted hsqldb dependency 2.5.0 to 2.4.1 as this causes test failures locally.  There is a ticket in the backlog to investigate and fix.
> DT-780 finishing off a couple of TODO's around population of return types.

- src/main/java/net/syscon/elite/api/model/PrisonToPrisonMove.java
- src/main/java/net/syscon/elite/api/model/ScheduledPrisonToPrisonMove.java
- src/main/java/net/syscon/elite/api/resource/OffenderMovementsResource.java
- src/main/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImpl.java
- src/main/java/net/syscon/elite/service/PrisonToPrisonMoveSchedulingService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_schedulePrisonToPrisonMove.java
- src/test/java/net/syscon/elite/service/PrisonToPrisonMoveSchedulingServiceTest.java
New endpoint on elite2 to support scheduling of prison to prison moves.
> DT-781 wiring in service layer to new endpoint for scheduling prison to prison moves.

- src/main/java/net/syscon/elite/repository/jpa/model/OffenderIndividualSchedule.java
- src/main/java/net/syscon/elite/repository/jpa/model/TransferCancellationReason.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderIndividualScheduleRepositoryTest.java
Additional field added to JPA entity to allow for the cancellation of an offender individual scheduled event.
> DT-818 additional JPA mapping to allow for cancellation of an offender individual scheduled event.

- src/main/java/net/syscon/elite/api/model/OffenderCell.java
- src/main/java/net/syscon/elite/api/model/OffenderCellAttribute.java
- src/main/java/net/syscon/elite/api/resource/AgencyResource.java
- src/main/java/net/syscon/elite/api/resource/impl/AgencyResourceImpl.java
- src/main/java/net/syscon/elite/service/AgencyService.java
- src/main/java/net/syscon/elite/service/AgencyServiceImpl.java
- src/test/java/net/syscon/elite/service/AgencyServiceImplTest.java
> NN-2599: Add cell resource and service

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/CourtEventCharge.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCharge.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCourtCase.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderBookingRepositoryTest.java
This change supports carrying over pre-existing court case hearing charges to new (additional) court hearings to mirror the behaviour of old NOMIS.  Note this is for court hearings linked to court cases.
> DT 865 changes for carrying over pre-existing court hearing charges

- src/main/java/net/syscon/elite/api/model/Contact.java
- src/main/java/net/syscon/elite/api/model/ContactDetail.java
- src/main/java/net/syscon/elite/service/ContactService.java
- src/test/java/net/syscon/elite/executablespecification/ContactStepDefinitions.java
- src/test/java/net/syscon/elite/executablespecification/steps/ContactSteps.java
- src/test/resources/features/booking_contacts.feature
Extends current offender contacts API to additionally return non next of kin contacts (docs suggest that was the intention but does not seem to have been implemented)
> Nn 2635 return offender official contacts

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/EventStatus.java
- src/main/java/net/syscon/elite/service/CourtHearingReschedulingService.java
- src/test/java/net/syscon/elite/service/CourtHearingReschedulingServiceTest.java
This service is support changes to court hearings dates and times.
It is quite common as court hearings get nearer the dates and/or times may need to be shuffled around.
> DT-893 new service to support rescheduling of court hearing dates.

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/CourtEventCharge.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCharge.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
Fix to ensure only active charges are carried over to new court events (hearings).
> DT-907 only active charges should be carried over to new court events (hearings).

- docker-compose-data-compliance.yml
- docker-compose-full.yml
- docker-compose.yml
This is just a fix to docker-compose and can go live whenever
> DT-897 Fix docker-compose so it works locally

- src/main/java/net/syscon/elite/service/CourtHearingCancellationService.java
- src/main/java/net/syscon/elite/service/CourtHearingReschedulingService.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_cancelCourtHearing.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_rescheduleCourtHearing.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_scheduleCourtCaseHearing.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_scheduleCourtHearing.java
- src/test/java/net/syscon/elite/executablespecification/steps/AuthTokenHelper.java
As part of discussions with the NART team it was decided the permissions to create. retrieve and update court hearings needs to be hardened.
> DT-929 adding permissions/role check for create, update and deletion of court hearings.

- src/main/java/net/syscon/elite/service/PrisonToPrisonMoveSchedulingService.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_cancelPrisonToPrisonMove.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest_schedulePrisonToPrisonMove.java
- src/test/java/net/syscon/elite/executablespecification/steps/AuthTokenHelper.java
Locking down prison to prison moves to a specific role.  Without this role you cannot do it.
> DT-940 adding a specific for handling of prison to prison moves.

- src/main/java/net/syscon/elite/api/resource/BookingResource.java
- src/main/java/net/syscon/elite/api/resource/impl/BookingResourceImpl.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/api/resource/impl/BookingResourceTest.java
- src/test/resources/net/syscon/elite/api/resource/impl/visits_with_visitors.json
- src/test/resources/net/syscon/elite/api/resource/impl/visits_with_visitors_paged.json
The endpoint was not returning the pagination data back correctly (wrong total elements and no pageable object). Also added end to end tests to make sure pagination is working as expected.
> NN-2751: Return pagination data and add integration test

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitInformationFilter.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitInformationRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/visits_with_visitors_filter_paged.json
Move filtering to repository in order to return correct page metadata.
> Nn 2793 visits pagination

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderNonAssociationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderNonAssociationsServiceTest.java
DT-1016 refactoring - linking the non-associations to booking JPA entity to simply retrieval.
> DT-1016 refactoring - linking the non-associations to booking JPA entity to simply retrieval.

- build.gradle
which upgrades hibernate-core to org.hibernate:hibernate-core -> 5.4.18.Final prior versions have security vulnerability
> DT-1020: upgrade hmpps-gradle-spring-boot plug in to 0.4.5

- src/main/java/uk/gov/justice/hmpps/prison/repository/impl/MovementsRepositoryImpl.java
Required try/catch around queryForObject
> DT-1034 🐛 Events not coming through

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/v1/NomisApiV1Resource.java
Visits endpoint object incorrect
> 🔧 DT-1035 - Update swagger for slots

- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/controller/DataComplianceController.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/listeners/DataComplianceEventListener.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/listeners/dto/ReferralRequest.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/dto/OffenderPendingDeletion.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/dto/OffenderPendingDeletionReferralComplete.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/model/OffenderAlertPendingDeletion.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/model/OffenderAliasPendingDeletion.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/model/OffenderBookingPendingDeletion.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/repository/OffenderPendingDeletionRepository.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralService.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/controller/DataComplianceControllerTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/events/listeners/DataComplianceEventListenerTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/DataComplianceEventPusherTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/repository/OffenderAliasPendingDeletionRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralServiceTest.java
Also surfacing offender alerts in the referral.
> GDPR-171 Replacing API call with SQS event to trigger referrals

- build.gradle
This should help resolve Kotlin OWASP warnings.
> DT-1066 updating to latest dps-gradle-spring-boot plugin and other dependency updates.

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderAssessmentResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderAssessmentResourceImpl.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/impl/InmateRepositoryImpl.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderAssessmentResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/InmateServiceImplTest.java
Correct problem with flag that was used for 2 diffenrent things.
Conveniently sorts a pathfinder issue 👍
> PAT-1200 Get all assessments for latest booking

- src/main/java/uk/gov/justice/hmpps/prison/api/model/Alert.java
This is really just a plaster to a wider problem e.g. using one model to represent multiple representations.
> DT-1089 small update to the docs to be more a representaive alert.  Note this is not ideal, more a workaround for now

- src/main/java/uk/gov/justice/hmpps/prison/api/model/PrisonerDetailSearchCriteria.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/PrisonerResource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonersResourceTest.java
Reverts ministryofjustice/prison-api#705
> Revert "DT-1095 validating offender no format as was causing a formatting exception further down the stack."

- src/main/java/uk/gov/justice/hmpps/prison/api/model/CellMoveResult.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderMovementsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BedAssignmentHistoryService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementUpdateService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDamageObligationService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderMovementResourceApiTest_moveToCell.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderMovementsResourceIntTest_moveToCellSwap.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/OffenderDamageObligationRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BedAssignmentHistoryServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/MovementUpdateServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDamageObligationServiceTest.java
- Tidy up Movement update service
- Improve swagger docs
- Improve damage obligation test
> NN-3016 return the bed assignment history sequence

- .circleci/config.yml
- build.gradle
Removed jdbc jar from lib folder and added as gradle dependency
> Dt 1247 use ojdbcjar gradle dependency

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AppointmentsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/BookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/sql/BookingRepositorySql.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/AppointmentsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AppointmentsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/BookingRepositoryTest.java
`PUT /appointments/{appointmentId}/comment` with body that is a ,possibly empty, JSON string
> DCS-746 'Amend booking appointment comment' operation.

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AppointmentsResource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AppointmentsResourceTest.java
* Use content type text/plain
* Extra tests for empty comment
> DCS-746.  'Amend booking appointment comment' operation.

- build.gradle
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderTransactionHistoryDto.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderTransactionHistory.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderTransactionHistoryRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/FinanceService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderTransactionHistoryResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/When_GetOffenderTransactionHistory_Then_ReturnCorrectJson.json
- Compute running balance
- Refactor tests into nested parts
> NN-3076 Compute running balance (WIP)

- helm_deploy/prison-api/templates/_envs.tpl
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-t2.yaml
- helm_deploy/values-t3.yaml
Graph of current memory usage can be found by going to [App Insights]( https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3WQQU%252BDQBCF7%252FyKCYkBkmIXCi0l1oM9qIcaY%252FDixWxhbEnYXZxd2tT444VapYmY7Gnem7dvvhrpTZHgMselaqRB0mB9wn6LhJBXqilen1SFD1wgLBbg1FRqJX1el441Hv8Y5Um2b5eQKcMryEqBtvVHv0NewwqFogM8ayzAXd149lDSBTySylFrRaew3lRKbbrGR2NwrpjW2WqihmswquAGu4nrhCwMfBa2L2OzlLGUJZdsEr84njW0yjfKDdjWa5P%252FjUnSSXwWM9Thang5yNg8jYaXe%252BT350f22P1ZEs%252FXSTSNI1%252Fs32naUdaNEJzKD4QO8DffDu%252BC7zbujlcNerA%252BwLqU7m%252B7EQTC …
> DT-1578: 🔨 Set max memory for jvm

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementUpdateService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocationTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AgencyServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/cells_with_capacity.json
Reverts ministryofjustice/prison-api#833
> Revert "NN-3102: cellsWithCapacity returns cells with zero operational capacity (WIP)"

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementUpdateService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocationTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AgencyServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/cells_with_capacity.json
Reverts ministryofjustice/prison-api#841
> Revert "Revert "NN-3102: cellsWithCapacity returns cells with zero operational capacity (WIP)""

- .circleci/config.yml
- build.gradle
- src/main/java/uk/gov/justice/hmpps/prison/web/config/SwaggerConfig.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/SwaggerValidatorIntTest.java
Fixed by upgrading to the latest DPS Gradle Plugin
> DT-1657 cve 2021 22112

- src/main/java/uk/gov/justice/hmpps/prison/api/model/AssessmentQuestion.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/AssessmentSummary.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentServiceTest.java
In a CSRA assessment there are some questions where more than 1 answer can be selected - at the moment that causes a server error.
> NN-3254: support multiple answers to csra question

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderAssessment.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderAssessmentRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderAssessmentRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/csra_ratings.json
Batch DB calls for CSRA ratings for multiple offenders. Also only return data for offenders that have assessments
> NN-3363: Improvements to new CSRA ratings endpoint

- src/main/java/uk/gov/justice/hmpps/prison/repository/LocationRepository.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/LocationRepositoryTest.java
> NN-3453: Prevent SQL error when getting residential locations and no top-level locations found

- .circleci/config.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Reverts ministryofjustice/prison-api#960
> Revert "DT-2253: ⬆️ Upgrade spring boot / kotlin"

- src/main/java/uk/gov/justice/hmpps/prison/aop/AuthorisationAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/CaseNoteRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/CaseNoteService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAddressService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDamageObligationService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationServiceImplTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/casenotes.json
Reverts ministryofjustice/prison-api#968
> Revert "DT-2321 Remove deprecated Case Note finder, handle access to data consistently"

- src/main/java/uk/gov/justice/hmpps/prison/aop/AuthorisationAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/CaseNoteRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/CaseNoteService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAddressService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDamageObligationService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationServiceImplTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/casenotes.json
Reverts ministryofjustice/prison-api#972
> Revert "Revert "DT-2321 Remove deprecated Case Note finder, handle access to data consistently""

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
This was caused by a DB trigger on the EXTERNAL_MOVEMENTS table (trigger id = `OFFENDER_EXTERNAL_MOVEMENTS_T1 `), which updates the OFFENDER_BOOKINGS STATUS_REASON column.
When using JPA, the execution order of the SQL statements is independent of when the changes are made. In our instance, the SQL to deactivate the EXTERNAL_MOVEMENTS was being run after the SQL to update the OFFENDER_BOOKINGS table - this caused the STATUS_REASON to be overwritten by the afore-mentioned trigger.
The real bug IMO is that this trigger runs even when an EXTERNAL_MOVEMENTS entry has ACTIVE = "N", but we cannot wait for that to be changed (if indeed Syscon are willing to update it at all).
> NN-3450: Get discharge-to-hospital endpoint to work on the first call

- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/service/OffenderDeletionService.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/AppModuleName.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/OffenderDeletionRepository.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/service/OffenderDeletionServiceTest.java
> GDPR-315: Prevent triggers executing on DELETE statement when 'cleaning' offender data

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateAlertService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementsService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
There seems to be a problem attaining an Oracle proxy connection. The username doesn't seem to exists and we think this is because the verify access checks are being triggered on the read only replication database where this user doesn't exists. Moving these checks to the service should ensure that the correct db is checked as the whole service is within a write transaction.
> NN-3589 fix connection proxy issues

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_getOffenderAlerts.java
New version of /api/bookings/{bookingId}/alerts/v2 with new contract (parameters, paging etc) added .
This allows clients to move to the new endpoint prior to the vulnerability being fixed.
> DT-2329 Added /api/bookings/{bookingId}/alerts/v2 as new contract 

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateAlertService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_getOffenderAlerts.java
- src/test/java/uk/gov/justice/hmpps/prison/service/InmateAlertServiceImplTest.java
NB the new endpoint still not being used in real world yet
> DT-2329 New Alert service used in new Booking Alert API

- src/main/java/uk/gov/justice/hmpps/prison/repository/InmateAlertRepository.java
so we know when it can be removed
> DT-2458 Log when alert service is processing legacy "query", 

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/ReleaseAPrisonerIntegrationTest.java
Reverts ministryofjustice/prison-api#1045
> Revert "NN-3603 remove case note creation as one is already created by a trigger"

- src/main/java/uk/gov/justice/hmpps/prison/api/model/AdjudicationDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/NewAdjudication.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjudicationsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AdjudicationsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/adjudication_by_number.json
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/new_adjudication.json
Also return offenderNo when retrieving
> NN-3742: Create adjudications using offenderNo not booking id

- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderActivitiesService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderActivitiesResourceTest.java
The new education endpoints should be accessible to all
> ESWE-214 prison-api endpoints should not have role protection

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderKeyDates.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToUpdateOffenderDates.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/SentenceCalculation.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderDatesResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/offender-key-dates-updated.json
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/sentence-after-offender-key-dates-update.json
https://dsdmoj.atlassian.net/browse/DT-2556
See [Slack message](https://mojdt.slack.com/archives/C02MV6MP933/p1637146006008500)
> DT-2556: include additional fields on the interface

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderDatesResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
https://dsdmoj.atlassian.net/browse/DT-2556
> DT-2556: log event to AppInsights; remove Hidden Swagger annotation

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjudicationsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AdjudicationRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AdjudicationsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
Also add missing validation for statement on update
> NN-3801: Remove adjudication search endpoint

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/ExternalMovementRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementsService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/ExternalMovementRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/MovementsServiceImplTest.java
This was a bit of a hack to help speed up a query but managed to get an appropriate index applied to production that should address the underlying issue 
This reverts commit 761302653a8c7a4409440039adad299d35f015a3.
> Revert "DCS-1452 adding date (#1168)"

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceAndOffences.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceTerm.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderSentence.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/sentences-and-offences-details.json
Adding the terms of a sentence to our sentence and offence payload.
> CRS-746 adding terms to payload.

- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
Also, added validation for offence codes on update
> NN-3972: Fix adjudication error when duplicate offence codes supplied

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderSentenceRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
Reverts ministryofjustice/prison-api#1223
> Revert "CRS-838 Removing like from CRD query."

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/NomisApiV1Resource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/v1/impl/NomisApiV1ResourceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/v1/impl/NomisApiV1ResourceTest.java
Reverts ministryofjustice/prison-api#1222
> Revert "SDI-147: 💥 Break create transactions endpoint"

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
https://dsdmoj.atlassian.net/browse/INC-293
> INC-293: mark getBookingIEPSummary endpoint as deprecated

- .circleci/config.yml
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/NomisApiV1Resource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/v1/impl/NomisApiV1ResourceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/v1/impl/NomisApiV1ResourceTest.java
Reverts ministryofjustice/prison-api#1232
> Revert "Revert "Revert "SDI-147: 💥 Break create transactions endpoint"""

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/OffenderBookingBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/OffenderBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/WebClientEntityBuilder.kt
Passing the 2 required parameters in during save rather than insisting on a instance variable that looked confusing
> SDI-152 Tiny refactor for webTestClient

- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
https://dsdmoj.atlassian.net/browse/INC-485
> INC-485: return default IEP level for a prison if there is no current IEP for a list of booking IDs

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderIepLevel.java
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/ExternalMovementTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/IEPTransferService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/BedAssignmentTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/CaseNoteTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/ExternalMovementTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/IEPTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/PrisonTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/TrustAccountServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/VisitBalanceTransferServiceTest.kt
These complement the existing integration test but add more error scenarios
> SDI-152 Unit tests for all new service 

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
https://dsdmoj.atlassian.net/browse/INC-481
> INC-481: mark BookingResource IEP endpoints as deprecated

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/LocationResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/SearchOffenderService.java
https://dsdmoj.atlassian.net/browse/INC-481
> INC-481: remove returnIep request param from getOffendersAtLocationDescription

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/transformers/OffenderBookingTransformer.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/bookings_by_nomsId.json
https://dsdmoj.atlassian.net/browse/INC-481
> INC-481: remove iepLevel request param from getPrisonerBookingsV2

- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToTransferOutToCourt.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyInternalLocationRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
Requires basic endpoint to transfer out to court, this is an amended version of the transfer-out (also not used in production)
> SDI-172 Add basic tests for returning from court

- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToTransferOutToCourt.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/CaseStatus.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/LegalCaseType.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderCourtCase.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/CourtEventRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderCourtCaseRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/DataLoaderRepository.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/OffenderBookingBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/OffenderCourtCaseBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/OffenderProgramProfileBuilder.kt
This requires the ability for the ALPHA version of court transfer out to associate with court events
Also the ability to create court cases and court hearings
> SDI-180 Test for court hearing events

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderTeamAssignment.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/Team.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderTeamAssignmentRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/storedprocs/OffenderAdminProcs.java
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/PrisonTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/TeamWorkflowNotificationService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/WorkflowTaskService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/PrisonTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/TeamWorkflowNotificationServiceTest.kt
The team that is assigned to the prisoner from the previous prison is notified using the workflow store procedure.
The store procedure is called because tis uses a Oracle queue and custom XML embedded in the SP
> SDI-184 Automatic transfer team notification

- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/PrisonTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/transfer/TrustAccountService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/PrisonTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/TrustAccountServiceTest.kt
Also refactor so service can accept if a prison transfer or a via court transfer
> SDI-184 Call trust accounts create on transfer via court

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/InstitutionArea.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderTeamAssignment.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderTeamAssignmentFunction.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/Team.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/TeamCategory.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/ActivityTransferServiceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/DataLoaderRepository.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/transfer/TeamWorkflowNotificationServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/BuilderHelpers.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/OffenderBookingBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/OffenderBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/OffenderCourtCaseBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/OffenderProgramProfileBuilder.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/WebClientEntityBuilder.kt
In preparation for creating a team and offender assignment builder the entities are now fully mapped and moved builders to own package for clarity
> SDI-187 Mapped team and moved builders

- .circleci/config.yml
- Dockerfile
Reverts ministryofjustice/prison-api#1287
> Revert "SDI-189: ✨ Try out buildx for multi arch builds"

- .circleci/config.yml
- Dockerfile
Reverts ministryofjustice/prison-api#1288
> Revert "Revert "SDI-189: ✨ Try out buildx for multi arch builds""

- src/main/java/uk/gov/justice/hmpps/prison/security/AuthenticationFacade.java
- src/test/java/uk/gov/justice/hmpps/prison/security/AuthenticationFacadeTest.java
issue found with verifyOffenderAccess.  It uses the isOverrideRole and the default annotation is defined as ROLE_
> NN-4171 ensure both roles methods strip ROLE_

- src/main/java/uk/gov/justice/hmpps/prison/repository/storedprocs/CopyProcs.java
This will copy across the workflow data associated with alerts
> DCS-1674 Call correct stored procedure

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
Reverts ministryofjustice/prison-api#1328
> Revert "DCS-1638 refreshing object after stored procedure execution"

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
Reverts ministryofjustice/prison-api#1331
> Revert "tmp logs"

- src/main/java/uk/gov/justice/hmpps/prison/service/transformers/OffenderEventsTransformer.java
- src/test/java/uk/gov/justice/hmpps/prison/service/transformers/OffenderEventsTransformerTest.java
Signed-off-by: mjwillis <michael.willis@digital.justice.gov.uk>
> INC-527 Handle new XTAG events ready for for re-indexing prisoner

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderProfileDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderProfileDetailRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/transformers/OffenderTransformer.java
Reverts ministryofjustice/prison-api#1335
> Revert "DCS-1638 testing water"

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderProfileDetail.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTest.java
Integration test wasn't actually ensure the data was written correctly so now do a GET.
(also actually fixed bug)
> SDI-256 Ensure profile code is actually saved

- build.gradle.kts
- SDI-261: 💩 Force pinning of versions so that upgrade versions ignores it each time
- SDI-257: 🔒️ Suppress false positive for log4j
> SDI-257: 🔒️ Suppress false positive for log4j

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceNewBookingTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/OffenderBookingBuilder.kt
Still need tests that assert store procedures are called, that requires a small refactor
> SDI-259 Added create booking integration tests describing most of the behaviour

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- SDI-296 Upgrade to Spring Boot 2.7.2
- SDI-296 Upgrade to gradlew 7.5
> mh SDI 296 spring boot 2.7.2

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OracleXtagEventsRepository.java
> SDI-333 Changes to event handling to improve latency

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ActivityTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BedAssignmentTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookNumberGenerationService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/CaseNoteTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/IEPTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/StaffAwareTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/TeamWorkflowNotificationService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/TrustAccountService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/VisitBalanceTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/WorkflowTaskService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceNewBookingTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/ActivityTransferServiceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BedAssignmentTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/CaseNoteTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/IEPTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/TeamWorkflowNotificationServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/TrustAccountServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/VisitBalanceTransferServiceTest.kt
The package will also contain services from creating a new booking hence the rename
> SDI-266 Package rename to reflect the scope of these services

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceNewOffenderTest.kt
> SDI-266 Basic validation integration test

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceNewOffenderTest.kt
> SDI-266 create offender advanced validation integration tests

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderImprisonmentStatus.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyInternalLocationRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyLocationRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/ImprisonmentStatusRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/ProfileTypeRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookingIntoPrisonService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferService.kt
Existing very good integration tests unchanged showing now behaviour changes
* TODO Restricted patients calls old method, need to understand if that is still need before removing old version
> SDI-266 New refactored create booking service

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepositoryExt.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookingIntoPrisonService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceRecallTest.kt
Old version still there for refeference
> SDI-266 Move to refactored version of recall

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/SmokeTestHelperService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceCourtTransfersTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/SmokeTestHelperServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonerTransferServiceTest.java
* Removes old version of recall
* Removed the service indirection for other refactored services
* Point services and tests and refactor services
* Removed dead code
* Reordered services so public stuff at top
> SDI-266 Clean up, and remove dead code

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/MovementReason.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderIndividualScheduleRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonToPrisonMoveSchedulingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonTransferService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTemporaryAbsenceArrivalTest.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/TemporaryAbsenceArrivalServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferServiceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonTransferServiceTest.kt
1. Existing TAP return moved to new service to share code
2. Existing TAP return bugs fixed by moving to new shared services
3. New functionality, return from TAP to different prison based on court return functionality
> SDI-266 TAP return refactor and return to different prison

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/DigitalWarrantResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/CourtOrder.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/CourtOrderRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/DigitalWarrantResourceImplIntTest.java
Adding more data to complete the booking. Trying to get to the point we can calculate release dates from the data entered. 
Could the approver please merge as well!
> MDWFP-23 adding court orders to digital warrant service.

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest.java
When discharging to hospital via Restricted Patients we change the case note text to say "Transfer" instead of "Release" because the offender is still under prison care. Release is generally interpreted as released into the community.
> SDI-429 discharge case note

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/MovementResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
Remove annotation for endpoints relied on by event message clients
> SDI-430 Add @SlowReportQuery annotation to prison-api

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderEventsController.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderEventsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderEventsControllerTest.java
Preparation: remove test poll endpoint
> SDI-450 Removal of the /events endpoint from prison-api

- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/CourtDateResult.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantServiceTest.kt
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/digital-warrant-court-date-results.json
Adding disposition code to court results. This will be used to calculate relevant remand for non-sentencing outcomes.
> MDWFP-37 adding disposition code to court results.

- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/CourtDateResult.kt
- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/WarrantCharge.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/WarrantCourtCase.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/WarrantSentence.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/DigitalWarrantResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/DigitalWarrantResourceImplIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantServiceTest.kt
Renaming warrant folder api classes to avoid documentation clashes.
> MDWFP-53 fixing clashing names with digital warrant api models.

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookingIntoPrisonService.kt
Reverts ministryofjustice/prison-api#1526
> Revert "SDIT-645: 🐛 Attempt to prevent duplicate bookings by grabbing lock on select"

- src/main/java/uk/gov/justice/hmpps/prison/api/model/digitalwarrant/WarrantCharge.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/digitalwarrant/DigitalWarrantServiceTest.kt
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/digital-warrant-court-date-results.json
Add outcome and court location to court results for use with the relevant remand calculator.
> MDWFP-96 adding outcome and court to court results.

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
> SDIT-786 Improve GET /api/agencies/{agencyId}/cellsWithCapacity

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocationProfile.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AgencyServiceTest.java
Reduce cartesian join as was still slow
> Improve GET /api/agencies/{agencyId}/cellsWithCapacity

- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
> Sdit 889 improve /bookings/{booking id} and /bookings/offender no/{offender no}

- build.gradle.kts
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
dowgrade hibernate-community-dialects:6.2.5 to 6.2.2
> Sentence test fix

- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
https://dsdmoj.atlassian.net/browse/NN-5430
> NN-5430: update other sanctions passed in the update request payload

- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest.java
This is called from POST /api/bookings/offenders endpoint
> SDIT-1120 Override check of SYSTEM_USER role is now deprecated

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
https://dsdmoj.atlassian.net/browse/NN-5606
This will allow the AdjudicationsAPI to call this endpoint
> NN-5606: add VIEW_ADJUDICATIONS role to POST:/offenders/adjudication-hearings

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceAndOffences.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderSentence.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/prison_resource_fixed_recall_calculable_sentence_envelope.json
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/prison_resource_single_calculable_sentence_envelope.json
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/sentences-and-offences-details.json
Renamed sentenceEnd to sentenceEndDate and added start date so as not to be confused with sentenceDate
> SDIT-1172 added sentence start date

- src/main/java/uk/gov/justice/hmpps/prison/service/GangService.kt
Fix bug when cell location is blank
> NON-280 Bug Fix

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/CellResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BedAssignmentHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/CellResourceHistoryTest.kt
> SDIT-1239 CellResource

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/NomisApiV1Resource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/v1/NomisApiV1Service.java
Use primary for all GETs involved in the Unilink issue
> SDIT-1287 Switch unilink get-transaction endpoints to primary

- src/main/java/uk/gov/justice/hmpps/prison/api/model/PrisonPeriod.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/TransferDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/Offender.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_timeline.kt
The updated code introduces the tracking of transfers in the offender's timeline. This functionality includes flagging transfers that happen through court or temporary absence. The commit also enhances existing methods for identifying types of movements and adds comprehensive unit tests to validate the new changes.
> SDIT-1298 Add transfer tracking to offender timeline

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderAssessmentResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/InmateRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderAssessmentResourceIntTest.kt
Reinstate the /category endpoint
> SDIT-1301 OffenderAssessmentResource fix

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/StaffResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/StaffService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AccessRoleMaintenanceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/StaffServiceImplTest.java
Add logging to check client users
> SDIT-1384 StaffResource

- .trivyignore
- SDIT-1303: 🔒️ Upgrade to latest plugin to suppress logback
- SDIT-1303: 🔒️ Suppress logback vulnerability
> SDIT-1303: 🔒️ Suppress logback vulnerability

- src/main/java/uk/gov/justice/hmpps/prison/service/StaffService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/StaffServiceImplTest.java
Refine logging of clients calling /staff endpoints
> SDIT-1384 StaffResource logging

- .circleci/config.yml
- run.sh
Reverts ministryofjustice/prison-api#1980
> Revert "SDIT-1126 prison-api startup takes a lot of cpu"

- helm_deploy/prison-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod-cp.yaml
- helm_deploy/values-preprod.yaml
Set one pod per node (5) in prod and tune memory and cpu
> SDIT-1126 prison-api startup takes a lot of cpu

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjustmentResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AppointmentsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/PrisonerResource.kt
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/UserResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjustmentService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AppointmentsService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/ContactService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/FinanceService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/HealthService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateAlertService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceImplIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_addPersonalCareNeed.kt
Appointments and Booking Resources
> SDIT-1444 Roles for Miscellaneous endpoints

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceImplIntTest_getOffenderRestrictions.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_getCaseNotes.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/BuilderHelpers.kt
GET /api/offenders/{offenderNo}/case-notes/v2
GET /api/offenders/{offenderNo}/case-notes/{caseNoteId}
GET /api/offenders/{offenderNo}/contacts
GET /api/offenders/{offenderNo}/offender-restrictions
> SDIT-1358 Remove SYSTEM_USER from remaining Resource files:

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_addresses.kt
* This is likely to change to allow viewing addresses for OUT prisoners when you have the correct roles
> SDIT-1526 Add test to sure weirdness for /offender/{nomsNumber}/addresess

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAddressService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_addresses.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAddressServiceImplTest.java
This over turns a previous decision to block this since the DPS connect team has:
- Found a user case for this
- Brings DPS into line with NOMIS
> SDIT-1526 allow /offender/{nomsNumber}/addresses to return for released prisoners

- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAddressService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_addresses.kt
- src/test/java/uk/gov/justice/hmpps/prison/dsl/Offender.kt
- src/test/java/uk/gov/justice/hmpps/prison/dsl/OffenderAddress.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAddressServiceImplTest.java
* fix foolish error when there are multiple bookings, so find the root offender for latest used offender record
> SDIT-1526 fix /offender/{nomsNumber}/addresses when multiple bookings

- src/main/resources/application-nomis-hsqldb.yml
- src/main/resources/application-nomis-local.properties
- src/main/resources/application-nomis-local.yml
- src/main/resources/application-nomis.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
> SDIT-1424 prison-api nomis-local spring profile is active in prod

- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonerSearchResourceIntTest.kt
> CDPS-628: Update outside location description to proper case prison name

- src/main/java/uk/gov/justice/hmpps/prison/api/model/LatestTusedData.kt
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderDatesResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderDatesResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
* Gets the latest TUSED dates from historical bookings for analysis in Calculate Release Dates
* Updates tests accordingly
> Creates an endpoint to get latest TUSED dates for an offender.

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingMovementsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderMovementsResource.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementUpdateService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingMovementsResourceIntTest_moveToCell_mockService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/MovementUpdateServiceTest.java
> SDIT-924 Lock check for PUT /api/bookings/{bookingId}/living-unit/{internalLocationDescription}

- helm_deploy/prison-api/values.yaml
- src/main/resources/application-nomis.yml
- **SDIT-1776: 🔧 Add more comment exceptions after reviewing mod security logs**
- **SDIT-1776: 🔧 Also decrease max lifetime**
> SDIT-1776: 🔧 Add more comment exceptions after reviewing mod security logs

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/StaffResource.java
- src/main/java/uk/gov/justice/hmpps/prison/security/VerifyAgencyAccess.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/StaffService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AgencyResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_getOffenderAlerts.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/KeyWorkerResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/MovementResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderAssessmentResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ScheduleResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/StaffResourceIntTest.kt
404 errors in the last few agency-related endpoints will now be 403s
> SDIT-1714 Change default value of accessDeniedError annotation to true for @VerifyAgencyAccess annotation

- helm_deploy/prison-api/values.yaml
- helm_deploy/values-preprod-cp.yaml
- helm_deploy/values-prod.yaml
Checked by running the following in log analytics:
```
AppRequests
| where AppRoleName == 'prison-api'
| where TimeGenerated > ago(7d)
| where ResultCode <> "401"
| where Url startswith "https://prison-api-preprod.prison"
| where ClientIP !in ("35.178.209.113","3.8.51.207","35.177.252.54","18.130.148.126","18.169.147.172","35.176.93.186","35.176.148.126","81.134.202.29","213.121.161.112/28","217.33.148.210","20.49.246.49","52.56.240.62","18.130.110.168","35.178.44.184","51.140.74.14","20.108.102.123","20.90.204.228","20.90.204.188","20.108.146.132","20.90.223.4","20.26.15.70","20.26.13.151","4.159.24.241","4.250.55.134","4.159.24.255","51.140.73.85","4.250.55.217","172.165.88.82","4.250.82.111","4.158.106.101","4.158.105.106","4.250.51.127","4.250.49.230","4.159.26.128","172.166.86.30","4. …
```
> SDIT-1771: 🔒️ Create ip allow list for preprod

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AppointmentsResource.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderIndividualScheduleRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AppointmentsService.kt
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AppointmentsResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/AppointmentsServiceImplTest.kt
And also DELETE /api/appointments/{id} and update of comments
> SDIT-1839 Lock timeout for POST /api/appointments/delete

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/CaseNoteRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/OffenderAlertRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/OffenderDamageObligationRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderContactPersonsRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderIndividualScheduleRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderProgramProfileRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OicHearingRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/PrisonerRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitInformationRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitorInformationRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/TemporaryAbsenceArrivalServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/UserCaseloadAndRoleMaintenanceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/PrisonerTransferServiceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/util/JwtAuthenticationHelper.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/JwtParameters.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/WithMockAuthUser.kt
Reverts ministryofjustice/prison-api#2199
> Revert "SDIT-1808: 🎨 Rename mocking of auth user token"

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonRollCountService.kt
> MAP-1277 Sort correctly using natural sorting

- build.gradle.kts
- src/main/java/uk/gov/justice/hmpps/prison/aop/ProxyUserAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/HsqlConnectionAspect.kt
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.kt
- src/main/java/uk/gov/justice/hmpps/prison/health/HealthInfo.java
- src/main/java/uk/gov/justice/hmpps/prison/health/ProductIdInfoContributor.kt
- src/main/java/uk/gov/justice/hmpps/prison/web/config/HsqlSimulatedProxyAopConfiguration.java
- src/test/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspectTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/model/bulkappointments/AppointmentsToCreateJsonTest.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_getCalculableSentenceEnvelope.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ResourceTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/StubUserSecurityUtilsConfig.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/TestController.java
- src/test/java/uk/gov/justice/hmpps/prison/health/HealthInfoTest.java
- src/test/java/uk/gov/justice/hmpps/prison/web/config/JwkMockServer.java
Reverts ministryofjustice/prison-api#2227
> Revert "SDIT-1593: ✨ Start to switch to authentication holder from kotlin lib"

- src/main/java/uk/gov/justice/hmpps/prison/api/model/Agency.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/AgencyDto.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyLocationRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/transformers/AgencyTransformer.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AgencyResourceIntTest.kt
Also optimise query to join to REFERENCE_CODES
> SDIT-1925 Add court type description

- src/main/java/uk/gov/justice/hmpps/prison/aop/AuthorisationAspect.kt
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AppointmentsService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/validation/CaseNoteTypeSubTypeValidator.java
- src/main/java/uk/gov/justice/hmpps/prison/web/config/AuditorAwareImpl.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/CaseNoteMovementServiceImplIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/validation/CaseNoteTypeSubTypeValidatorTest.java
- **SDIT-1593: ✨ More switching to authentication holder**
- **SDIT-1593: ✨ More switching to authentication holder**
> SDIT-1593: ✨ More switching to authentication holder

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
OrderColumn would fill list will nulls if first sequence was greater than 1 causing a NPE
> SDIT-1933 Fix OffenderBooking.offenderPhysicalAttributes mapping

- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/AbstractConnectionAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.kt
- **SDIT-2056: 🥅 Rethrow proxy session user errors**
> SDIT-2056: 🥅 Rethrow proxy session user errors

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/FinanceController.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/NomisApiV1Resource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/FinanceService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/v1/impl/NomisApiV1ResourceIntTest.kt
- Updated the allowed roles
- Updated the tags
- Updated the documentation
- Attempted to write a test
> HMAI-111 Make unilink endpoints suitable for HMPPS INTEGRATION API

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AgencyResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AgencyResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/AgencyServiceTest.java
the GET /api/agencies/{agencyId}/locations/type/{type} is no longer being called by any app
> MAP-1935 removed unused endpoint

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/PrisonerCreationService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_newOffender.kt
Expected to only be used for testing when needing prisoners to do a merge.
> SDIT-2406 - allow creation of prisoners with same name when required.

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
We need to create some prisoners in dev for Milsike so the easiest way to do this seems to be by creating them manually using the API. Once we've added the prisoners that we need we can remove these roles. We only need this for dev.
> Temporarily add access to offender write endpoints for HMPPS Integration API

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerSearchService.kt
NPE fix (bad data: 1 old movement has no movement type)
> SDIT-2790 Incorrect lastAdmissionDate in prisoner-search - fix

- build.gradle.kts
This reverts commit cc607855f8bc125dba4e756055fc29f67078b4b7.
> Revert "SDIT-2967: ⬆️  Upgrade plugin, kotlin etc. (#2456)"

- build.gradle.kts
Reverts ministryofjustice/prison-api#2459
> Revert "Revert "SDIT-2967: ⬆️  Upgrade plugin, kotlin etc. (#2456)""

- src/main/java/uk/gov/justice/hmpps/prison/service/ImageService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ImageResourceIntTest.kt
Ensure a separate update is done.
> SDIT-2985 Prisoner-search image id not updated if uploaded/edited on DPS

- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerSearchService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonerSearchResourceIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/dsl/OffenderBooking.kt
Fix recall detection and non-prison transfers and tidy up
> SDIT-3049 Add military flag and previous prison to prisoner-search
