ministryofjustice/prison-api

- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
This occurs when the user is an RO with global search,  has no active caseloads (as most won't) and provides no offender numbers
> DCS-383 Converting 500 response into correct 400 

- src/main/java/net/syscon/elite/repository/jpa/model/CaseStatus.java
- src/main/java/net/syscon/elite/repository/jpa/model/DisciplinaryAction.java
- src/main/java/net/syscon/elite/repository/jpa/model/EventStatus.java
- src/main/java/net/syscon/elite/repository/jpa/model/EventType.java
- src/main/java/net/syscon/elite/repository/jpa/model/LegalCaseType.java
- src/main/java/net/syscon/elite/repository/jpa/model/MilitaryBranch.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCourtCase.java
- src/main/java/net/syscon/elite/repository/jpa/model/ReferenceCode.java
- src/main/java/net/syscon/elite/repository/jpa/repository/ReferenceCodeRepository.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderBookingRepositoryTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
This change mainly includes support for retrieval of reference codes (and associated refactoring) so it can be used during the creation of court hearings.
> DT-601 changes to support retrieval of references codes in relation court hearing creation.

- src/main/resources/application-nomis.yml
Spring Security only applies the JWT issue validation if the config
property for issuer URI exists.  We want to turn it off as we have
multiple URIs for the Auth server but a multiple issuer scenario is
not supported.
> DT-370 Remove JWT issuer verification

- src/main/java/net/syscon/elite/web/config/JwkClient.java
- src/test/java/net/syscon/elite/web/config/ClientTrackingTelemetryModuleTest_JwkClient.java
- src/test/java/net/syscon/elite/web/config/JwkMockServer.java
- src/test/resources/application-test-jwk.yml
Use the existing RemoteJWKSet to retrieve the JWK set as this supports caching out of the box.  And is standard.
> DT-609 remote jwk set

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
Having viewed court events populated via C-NOMIS and the API I noticed 2 fields were being defaulted in C-NOMIS.  This change mirrors those default values when using JPA to create court events.
> DT-604 minor change to ensure default values are popualated for court events.

- src/main/java/net/syscon/elite/service/support/LocationProcessor.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest.java
- src/test/java/net/syscon/elite/service/support/LocationProcessorTest.java
Currently the location formatter will titlecase most abbreviations, resulting in rooms showing up as "Vcc Room 1", for example. This change introduces a list of abbreviations to be excluded from titlecasing and adds a test for the specific method.
> Nn 2493 location casing update

- src/main/java/net/syscon/elite/service/BadRequestException.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/main/java/net/syscon/elite/web/handler/ControllerAdvice.java
- src/test/java/net/syscon/elite/api/resource/impl/OffenderMovementsResourceImplIntTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
Change to return bad request if the supplied date range for court hearings is incorrect i.e. to before start.
> DT-651 small improvement to tighten validation of request for court hearing retrieval

- src/test/java/net/syscon/elite/aop/connectionproxy/OracleConnectionAspectTest.java
Add tests to illustrate the different outcomes for a Nomis and non-Nomis connection.
> DT-635 Add tests for Oracle Connection Aspect

- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/main/java/net/syscon/elite/repository/jpa/model/Gender.java
- src/main/java/net/syscon/elite/repository/jpa/model/Offender.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderBooking.java
- src/main/java/net/syscon/elite/repository/jpa/model/OffenderCourtCase.java
- src/main/java/net/syscon/elite/repository/jpa/repository/OffenderRepository.java
- src/main/java/net/syscon/elite/service/CourtHearingsService.java
- src/test/java/net/syscon/elite/repository/jpa/repository/OffenderRepositoryTest.java
- src/test/java/net/syscon/elite/service/CourtHearingsServiceTest.java
PR includes some minor JPA annotation tidy ups as well.  Mainly around the optional = false attribute on ManyToOne annotations.  This is to aid lazy loading of non-collection attributes.
> DT-663 adding intial cut of offender jpa entity.

- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
In whereabouts, we show historical records for offenders who may have transferred out of the establishment. Users still need to be able to pay them for outstanding activities even if the offender is no longer in that caseload. This removes the check limiting attendance updates to bookings currently in the user's caseload.
> NN-2447: Allow updating attendance for bookings outside of caseload

- build.gradle
- src/main/java/net/syscon/elite/repository/jpa/model/CourtEvent.java
- src/test/java/net/syscon/elite/repository/jpa/repository/CourtEventRepositoryTest.java
The relationship between court events and court cases should be optional.
A real world example of this would be a prisoner has been asked to go to court as a witness, so it is not linked to their specific court case(s).
> DT-696 court events relationship to court cases is optional.

- src/main/java/net/syscon/elite/api/resource/BookingResource.java
- src/main/java/net/syscon/elite/api/resource/impl/BookingResourceImpl.java
- src/test/java/net/syscon/elite/executablespecification/BookingStepDefinitions.java
- src/test/java/net/syscon/elite/executablespecification/steps/BookingAlertSteps.java
- src/test/resources/features/booking_alerts.feature
Ran
```
requests
| where cloud_RoleName == 'elite2-api'
| where name contains 'getOffenderAlertsByOffenderNo'
```
over the last two months to check it wasn't used in production (or dev).
Also ran
```
requests
| where cloud_RoleName == 'elite2-api'
| where url contains 'alerts'
| where name startswith 'GET'
| where url contains 'offenderNo'
```
for good measure too :grin:
> DT-704: Remove unused offender no alerts endpoint

- src/main/java/net/syscon/elite/repository/impl/OffenderDeletionRepositoryImpl.java
Background, if anyone's interested:
When running in T3, I've just recently started finding that the transaction 'hangs' and I see a blocking session appear in v$session.  I end up having to get the session killed manually.  This used to work ok.
However, I can still successfully point a local instance of Elite2 API to T3 and delete the same offender without problem. 🤷‍♂️ 
I'm hoping that the extra (excessive) logging will help pinpoint why there's an issue!
> GDPR-120 Adding extra logging to help debug deletion script issue

- src/main/java/net/syscon/elite/service/CourtHearingReschedulingService.java
- src/test/java/net/syscon/elite/service/CourtHearingReschedulingServiceTest.java
C-NOMIS has background jobs that expires hearings that are in the past.  However we cannot (should not) rely on this.  This change ensures changes to existing scheduled court hearings can only be done on those with a date already in the future.
> DT-893 tightening up validation on existing scheduling hearing being in future

- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/repository/jpa/repository/DuplicateOffenderRepository.java
When running against an Oracle DB the
extra ';' was causing issues, even though
the integration test against HSQLDB was running
fine.
> GDPR-57 Fixing duplicate detection SQL

- src/main/java/net/syscon/elite/api/model/VisitWithVisitors.java
Swagger was picking up `v1/Visit` model and generating wrong docs as a result.
> NN-2415: Fix Swagger picking up wrong Visit model

- src/main/java/net/syscon/elite/api/model/VisitDetails.java
- src/main/java/net/syscon/elite/api/model/VisitWithVisitors.java
- src/main/java/net/syscon/elite/api/resource/BookingResource.java
- src/main/java/net/syscon/elite/api/resource/impl/BookingResourceImpl.java
- src/main/java/net/syscon/elite/repository/BookingRepository.java
- src/main/java/net/syscon/elite/repository/impl/BookingRepositoryImpl.java
- src/main/java/net/syscon/elite/service/BookingService.java
- src/test/java/net/syscon/elite/executablespecification/steps/BookingVisitSteps.java
- src/test/java/net/syscon/elite/repository/BookingRepositoryTest.java
- src/test/java/net/syscon/elite/service/BookingServiceTest.java
There were two models called `Visit`, one of which was in `v1`. Swagger was picking up that one anywhere where we use Visit, including in the next and last visit endpoints. That resulted in the generated response docs being wrong, as the those APIs return the elite Visit model.
> NN-2738: Fix visit details swagger docs

- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/dto/OffenderPendingDeletion.java
- src/main/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralService.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/controller/DataComplianceControllerTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/events/publishers/DataComplianceEventPusherTest.java
- src/test/java/uk/gov/justice/hmpps/nomis/datacompliance/service/DataComplianceReferralServiceTest.java
Renaming to be a bit more explicit - an offender record can
have multiple entries in the OFFENDERS table which are
aliases for the same person and have their own offender id.
> GDPR-160 Renaming field in SQS event

- README.MD
Change to bring in-line with other Spring apps.  Note the old /ping will still work (for now).
> DT-1019 small tweak to ping details for the prison-api to use Springs default /health/ping.

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/HealthIntTest.java
A recent change to later version of Spring (update to later version) included changes to health check config which went unnoticed.
This test adds coverage to ensure future changes get picked up first.
> DT-1066 adding integration test for health checks on back of spring boot changes

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/MovementResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/MovementsRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/sql/MovementsRepositorySql.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/MovementResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/MovementsRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/MovementsServiceImplTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/movements_out_on_given_day.json
Changes:
Updating existing endpoint (with non-braking change) to add an optional request query parameter 'movementType' to filter the movements 'out' for a given date.
This enables PECS (Book a Secure Move) to work out the number of releases for a given agency on a specific date.  Other existing endpoints were considered but did not really make sense in terms of easily changing.  Adding a new endpoint seemed like overkill.
> P4-2813 adding (optional) non-breaking movement type filter param to movements out for given date endpoint so can filter by type where needed.

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBookingTest.java
**Changes:**
BaSM is seeing a `NullPointer` exception when trying to schedule court hearings for bookings with a court case id.
`"java.lang.NullPointerException: Cannot invoke \"uk.gov.justice.hmpps.prison.repository.jpa.model.OffenderCourtCase.getId()\" because \"cc\" is null\n\tat uk.gov.justice.hmpps.prison.repository.jpa.model.OffenderBooking.lambda..."`
I have not actually been able to recreate this locally but would like to try this to see if it resolves it.
> P4-2976 trialing a change to see if it resolves an issue in production

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/UserResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/UserService.java
- src/test/java/uk/gov/justice/hmpps/prison/executablespecification/UserStepDefinitions.java
- src/test/java/uk/gov/justice/hmpps/prison/executablespecification/steps/UserSteps.java
- src/test/java/uk/gov/justice/hmpps/prison/service/UserCaseloadAndRoleMaintenanceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/UserServiceImplTest.java
- src/test/resources/features/users.feature
Found endpoints that were being used by running
```
requests
| where cloud_RoleName == 'prison-api'
| where name startswith "GET /api/users"
| distinct name
```
and got results
```
| GET /api/users/ |  
  | GET /api/users/{username} |  
  | GET /api/users/{username}/access-roles/caseload/{caseload} |  
  | GET /api/users/local-administrator/available |  
  | GET /api/users/me |  
  | GET /api/users/me/caseLoads |  
  | GET /api/users/me/caseNoteTypes |  
  | GET /api/users/me/locations |  
  | GET /api/users/me/roles
```
This PR then removes
``` 
@GetMapping("/access-roles/caseload/{caseload}/access-role/{roleCode}")
@GetMapping("/caseload/{caseload}")
@GetMapping("/local-administrator/caseload/{caseload}")
@GetMapping("/staff/{staffId}")
```
> DT-2327: ♻️ Remove unused endpoints

- src/main/java/uk/gov/justice/hmpps/prison/service/LocationService.java
Pretty certain this is always blank, so logging to double check prior to its removal
> DT-2332 Log query parameter prior to removal

- src/main/java/uk/gov/justice/hmpps/prison/service/curfews/OffenderCurfewService.java
Was formerly just allowing ROLE_SYSTEM_USER.
Now additionally allows ROLE_VIEW_PRISONER_DATA.
This allows the CVL system client to avoid needing ROLE_SYSTEM_USER
HDC still OK as it currently uses ROLE_SYSTEM_USER.
> CVSL-339: Wider roles allowed for HDC get status endpoints

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/ReferenceDomainResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/ReferenceDomain.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/ReferenceDomainRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/ReferenceDomainService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ReferenceDataResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/executablespecification/steps/AuthTokenHelper.java
- src/test/java/uk/gov/justice/hmpps/prison/service/ReferenceDomainServiceImplTest.java
Endpoint is likely to only be used by developers who want to guess at the domain they need for other APIs
- Use JPA Repository for domain rather then SQL version since this is standard going forward
- Use JsonPath for testing rather than json file assert that is confusing
> SDI-76 New endpoint to retrieve list of domains

- src/main/java/uk/gov/justice/hmpps/prison/api/model/ReferenceCode.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/ReferenceDomainResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/ReferenceDataRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/ReferenceDomainService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/ReferenceDataResourceTest.java
The previous url was badly named as `/domains/{domain}` and also returns a paged result that almost certainly isn't required.
New url is `/domains/{domain}/codes`  and is unpaged. Also sub-codes is never returned since in live it is *never* requested
> SDI-78 Create un-paged version of codes for a domain

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenceResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/reference/OffenceService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenceResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/reference/OffenceServiceTest.kt
Also, in the creation of statutes or ho_codes, do not throw a 409 exception if a record already exists with the same PK, instead just skip that record.
> OFFENCES-81 Change offence related POST  and PUT endpoints to accept Lists rather than single objects

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderProfileDetail.java
Any row in OFFENDER_PROFILE_DETAILS with  a null code was accidentally not being read via JPA due to the mapping.
This change allows them to be read so that a row for YOUTH can be updated with the new code; without this both JPA and the NOMIS tore procedure will try to create the a row with the same primary key
> SDI-256 Ensure profiles with no code can be updated to prevent 2 rows being created.

- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceNewBookingTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/DataLoaderRepository.kt
- src/test/java/uk/gov/justice/hmpps/prison/util/builders/BuilderHelpers.kt
It uses the BuilderContext to group all the data helper functions, I think this is a better approach then adding to the base class that is too big as it stands
> SDI-259 Moved duplicate helpers to single file

- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToDischargePrisoner.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/movement_discharge_2.json
Currently, the RP API calls discharge to hospital for releasing prisoners IN prison. But it also handles prisoners released but fixes up the existing external movement if the `to agency` is incorrect.  This is use in the migration process or correction of an incorrectly NOMIS released RP prisoner.  The `from agency` SHOULD NOT be corrected as it break MPC / prisoner indexer if the location is not a prison which will be the case if the `supportingLocationId` is OUT. It also makes no sense to change the `fromLocation` without also changing the previous external IN movements to match, otherwise the prisoner will look like they have magically JUMPED to a new prison before being released.
> INC-647 From Agency location is not updated on an external movement update for an already released prisoner

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/Offender.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBooking.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderBookingTest.java
It turns out there is some old bad data in NOMIS where the release movement time is before the admission movement time (seems particularly prevalent around TAPs). This caused movements to be processed out of sequence when calculating the PrisonerInPrisonSummary. The fix being to process the movements in sequence order rather than movement time order.
> SDI-378 Fix null pointer when calculating PrisonerPeriod

- src/test/java/uk/gov/justice/hmpps/prison/executablespecification/AllFeatureTest.java
- src/test/resources/features/booking_details.feature
- src/test/resources/features/users.feature
When adding some details to the sentence calculation endpoints I changed the configuration of the integration tests to allow me to debug locally. This was accidentally committed and merged in this PR.
https://github.com/ministryofjustice/prison-api/pull/1286
I have reverted this change in this PR. However this resulted in a few failing tests. I have narrowed down the cause of these failures. 
Firstly there were some failing tests in `features/users.feature`. This is because an endpoint was removed in the PR 
https://github.com/ministryofjustice/prison-api/pull/1334
I have removed these tests.
The only other failure was in `features/booking_details.feature`. I don't know what the cause of this is as I'm unfamiliar with this area of prison api, but I can see it was most likely introduced in …
> Reverting change to AllFeatureTest which stopped some tests running.

- src/test/java/uk/gov/justice/hmpps/prison/executablespecification/steps/BookingAssessmentSteps.java
- src/test/resources/features/booking_details.feature
data setup for the prisoner A1234AD has the following
* calc level - LOW
* review level - null
* override level - MED
The new rules state that this will no longer be selected first, as it either needs a review level, or calculated as long as override is not present.
Given this data may be used elsewhere its easier to simply exclude it from the test set, given its now invalid.  Also removed from the non CSRA test as this uses the same step definition data.  The other tests provide enough coverage for the non CSRA one.
> NN-4508 remove prisoner from test as data is setup incorrectly

- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
Switched primary db (via non-readonly transaction) for 2 endpoints used by ES, this is a temporary fix for issue caused by replica being out of date when a xtag trigger fires.
Tested locally by upping logging level which shows the "master" database is selected with the annotation on
> SDI-416 Switched primary db

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/ExternalMovement.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffendersResourceTransferImpTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/ExternalMovementTransferServiceTest.kt
Minor defect fix; the TAP out movement location (city or address) was incorrectly being copied to IN movement when returning to a different prison; NOMIS does not do this, it only does it returning to same prison
> SDI-266 Transfer by TAP should copy address/city to new movement

- src/main/java/uk/gov/justice/hmpps/prison/repository/sql/ScheduleRepositorySql.kt
as per https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#/schedules/getEventsByLocationId both endpoints used by whereabouts.
> NN-4465 filter on scheduled only

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OicHearingResponse.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjudicationsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AdjudicationsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
new amend endpoint to simplify the adjudications api when editing a hearing.  Originally it was assumed nomis would only allow a delete / create however this is not the case as its a new set of apis.
> NN-4598 amend hearing endpoint

- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AppointmentsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/util/MdcUtility.java
- src/main/java/uk/gov/justice/hmpps/prison/web/filter/EventPropagationFilter.java
- src/test/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspectTest.java
- src/test/java/uk/gov/justice/hmpps/prison/web/filter/EventPropagationFilterTest.kt
Currently the NOMIS context can leak between connections. This has an impact on the suppression of XTag events where the NOMIS MERGE context was not applied for some connections, or was left in place for others - both incorrectly.
This PR should clear the NOMIS context whenever a connection to the primary database is acquired and makes sure the MERGE context is used where attempting to suppress XTag events.
> SDI-433 Tidy NOMIS context for write connections

- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.java
- src/test/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspectTest.java
We think we've found a bug where clearing the session when closing a Proxy connection then breaks the session context thereafter. Any further calls to set_context don't work.
This needs fixing properly but in the meantime remove the clear session recently added to all update connections which can only make things worse.
> SDI-429 Don't clear the session - it's then broken forever

- src/main/java/uk/gov/justice/hmpps/prison/aop/ProxyUserAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/AbstractConnectionAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/HsqlConnectionAspect.java
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/NomisConfigurer.kt
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspect.kt
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/ProxySessionClosingConnection.kt
- src/main/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/ResettableContextConnection.kt
- src/test/java/uk/gov/justice/hmpps/prison/aop/connectionproxy/OracleConnectionAspectTest.kt
We know that the NOMIS connections are being configured correctly now so we can remove some of the extra logging. I think all we need to know is:
* when a proxy user is used
* when a special connection is opened
* when a special connection is closed
We can assume that everything works as any exceptions will be logged in App Insights as will the failing request.
> SDI-464 Tidy up logging around NOMIS connections

- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToCreate.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookingIntoPrisonService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonerCreationService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_newOffender.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/PrisonerCreationServiceTest.kt
This allows WPIP to use a single transactional endpoint to create a prisoner and receive them into prison at the same time
> SDI-489 Optional create a booking when a prisoner is created

- src/main/java/uk/gov/justice/hmpps/prison/api/model/ImageDetail.java
Added some example values for ImageDetail model to ensure that prism simulator used by https://github.com/orgs/ministryofjustice/teams/hmpps-integration-api-admin-team is able to return realistic response data.
https://mojdt.slack.com/archives/C012FNNQ4A3/p1676903324729199
> Add examples to ImageDetail model

- src/main/java/uk/gov/justice/hmpps/prison/api/model/adjudications/AdjudicationDetail.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/OpenApiDocsDuplicateTest.kt
Duplicate schemas do not render in the swagger docs - only one version will be displayed everywhere
A couple of duplicates were fixed a couple of weeks ago and this changes another and ignores an instance that affects display of the V1 APIs
> Adding a test to detect duplicate OpenAPI schemas

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/receiveandtransfer/BookingIntoPrisonService.kt
- Revert "Revert "SDIT-645: 🐛 Attempt to prevent duplicate bookings by grabbing lock on select (#1526)" (#1528)"
- SDIT-645: 🐛 Use selected bookings rather than old bookings on offender
> SDIT-645: 🐛 Use selected bookings rather than old bookings on offender

- src/main/java/uk/gov/justice/hmpps/prison/api/model/Alert.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/Alias.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/AssignedLivingUnit.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/InmateDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenceHistoryDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderIdentifier.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceTerms.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/PhysicalAttributes.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/PhysicalCharacteristic.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/PhysicalMark.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/ProfileInformation.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/SentenceCalcDates.java
This removes all deprecated "required" fields in Swagger Schema annotations for the InmateDetail and all sub models (basically all the models required to call the `/api/offenders/:offenderNo` endpoint. This ensures that any client code that gets generated using the openapi-generator will not be generated with required fields. Instead the models generated will have optional fields.
> [DSE-1129] remove all required swagger docs fields for InmateDetail

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OicHearingResultRequest.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AdjudicationsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
When setting the independent adjudicator there will be no associated staff id therefore allow nulls when creating or amending hearing results
> NN-5049 allow null adjudicator

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjudicationsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OicSanctionRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
1. adding test case to avoid NPE in sanction compensation amount (optional value).
2. adding flushing to avoid (hopefully) error in trigger:
exceptions
| where cloud_RoleName == "prison-api"  and operation_Id == "4994d07eaf4243b2b5ec419eb600efd6"
ORA-20999: ORA-04091: table OMS_OWNER.OFFENDER_OIC_SANCTIONS is mutating, trigger/function may not see it
ORA-06512: at "OMS_OWNER.OFFENDER_OIC_SANCTIONS_T1", line 29
ORA-06512: at "OMS_OWNER.TAG_ERROR", line 169
ORA-06512: at "OMS_OWNER.OFFENDER_OIC_SANCTIONS_T1", line 38
ORA-04088: error during execution of trigger 'OMS_OWNER.OFFENDER_OIC_SANCTIONS_T1'
> Nn 5036 npe fix

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderCaseNote.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderCaseNoteRepository.java
Currently `author` is eager loaded as a N + 1 type query, when showing all case notes in DPS this leads to 100s of separate `select` from `staff_members` table. This change means that is all done via a `join` instead.
Avoiding high number of separate SQL select held when latency with database is high (e.g when in AWS)
> SDI-777 Fetch author for case notes for `findAll`

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/BedAssignmentHistory.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/BedAssignmentHistoriesRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BedAssignmentHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BedAssignmentHistoryServiceTest.java
Calls to this endpoint e.g. /api/cell/NMI/history/2023-04-28
result in ( n * 3)  + 1 SQL for each bed history record, each booking and offender record was loaded by individual and there was a separate repo call for the internal location that was already loaded
> SDI-778 Fetch booking/offender for bed histories by prison and date

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyInternalLocationRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AgencyServiceTest.java
For /agencies/{agencyId?/cellsWithCapacity cell profile attributes are currently loaded via a separate repo call which results in a n + 1 query.
For this endpoint only force a join fetch to reduce to a single SQL call to avoid latency issues when Oracle is move to AWS
> SDI-786 Fetch internal location profiles to avoid n + 1 SQL

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/Address.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/AgencyLocationRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AddressTransformer.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/PersonAddressRepositoryTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAddressServiceImplTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/PersonServiceTest.java
Currently this version of endpoint is returning prison phones numbers and address and phones numbers for each address.
Each prison has a single address and 2 numbers and each address has the the same 2 numbers. There is around 127 prisons.
Convert the n * 3 + 1  query to a single Cartesian Product join - we can do this because we know there is a "small" number of prisons and each has a single address and 2 numbers.
Phones and Addresses need to become a set else Hibernate can not load addresses and phones at same time. There is only one primary address per prison but the impact of this PR is the phone numbers might be returned in a different order (though no clients even read the phones let alone rely on the order rather than the type)
> SDI-779 Remove n + 1 SQL for deprecated GET /api/agencies/prison

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/VisitVisitor.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderContactPersonsRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/VisitVisitorRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/BookingServiceTest.java
This currently does an (n * 2) + 1 SQL query, since for each visitor it loads
- The lead visitor contact
- For each visitor
- The person contact
- The person
This service is a mixture of pure JPA and a SQL sub select - to keep the sub-select and to just optimise the visitor/contact part just the later is moved to use our JPA. But that still requires a repo findBy to pass-through a list of person ids or visitids.
It would be preferable to convert the entire endpoint to pure JPA to improve readability
> SDI-803 Remove n + 1 SQL for /api/bookings/{bookingId}/visits-with-visitors

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AdjudicationsResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OicHearingResultRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AdjudicationsService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AdjudicationsResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceIntTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/AdjudicationsServiceTest.java
Allows adj api to check if an hearing results has been added in NOMIS - in this instance will then lock down the report in the DPS service as its basically clobbered.
> NN-5100 Get OIC Hearing results endpoint

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderTransactionHistory.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderTransactionHistoryServiceTest.java
There is n + 1 SQL for transaction history due to the 1 to many relationship for transaction details .
Solution:
1. Add batch to @BatchSize relatedTransactionDetails to use `IN` query rather than multiple individual selects
2. Also ensure only the filtered transactions are used in the `IN` query by evicting redundant transaction from Hibernate cache
> SDI-805 remove n + 1 query for transaction use batch size

- src/main/java/uk/gov/justice/hmpps/prison/api/model/ImageDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderImage.java
- src/test/java/uk/gov/justice/hmpps/prison/service/ImageServiceImplTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/getimagesbyoffender.json
The captureDate property of `ImageDetail` doesn't contain the time. This PR adds a new property `captureDateTime` to expose add the time to the image detail endpoints.
These changes were based on the changes made by @emileswarts in [this PR](https://github.com/ministryofjustice/prison-api/pull/1594). As our team now has permissions to branch and PR on Prison API. We've redone the changes.
> HIA-360 Add active captureDateTime to ImageDetail response model

- src/main/java/uk/gov/justice/hmpps/prison/api/model/ImageDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderImage.java
- src/test/java/uk/gov/justice/hmpps/prison/service/ImageServiceImplTest.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/getimagesbyoffender.json
Expose `active` field to allow clients to select the most relevant images.
> HIA-360 Add active field to ImageDetail response model

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderSentenceResource.java
The 200 response for the `GET /api/offender-sentences/booking/{bookingId}/sentenceTerms` endpoint incorrectly documented that the response body is a single JSON object instead of a list of objects, see [/api/offender-sentences/booking/{bookingId}/sentenceTerms](https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#/offender-sentences/getOffenderSentenceTerms) in dev.
Let the Swagger annotation document the response body from the return type of the controller method for the API endpoint in order to document it being a list of objects.
Before | After
-- | --
</figure>
> HIA-292: Fix incorrect Swagger documentation for sentence terms endpoint

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceTerm.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderSentenceTerms.java
Adding examples makes it possible to quickly create simulators based on only the OpenAPI specification for services that depend on the Prison API. The HMPPS Integration API relies on this style of testing made possible by a tool called Prism.
> Add examples of offender sentence terms to OpenAPI spec

- src/main/java/uk/gov/justice/hmpps/prison/api/model/calculation/CalculableSentenceEnvelope.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/SentenceCalcType.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/prison_resource_single_calculable_sentence_envelope.json
Minor amendment to include the currently calculated (NOMIS) and user-overridden dates for the current booking. This will help in determining release in errors within a systemic comparison with the Calculate Release Dates Service
> CRS-1365 amend prison api to add all known releasedates

- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
To allow this change to work correctly, the following clients that have SYSTEM_USER and call this endpoint need updating:
categorisation-tool -> needs VIEW_ASSESSMENTS OR VIEW_PRISONER_DATA role
manage-pom-cases-api  -> already has VIEW_PRISONER_DATA (dev/preprod) role - but needs the role in PROD
manage-soc-cases-admin  -> already has VIEW_PRISONER_DATA role (dev/preprod)- but needs the role in PROD
The following clients call this endpoint but do not need updating:
pathfinder-admin -> already has VIEW_PRISONER_DATA role - no change
prison-staff-hub -> does not have SYSTEM_USER _ROLE - no change
> SDIT-1120 Change override roles when viewing assesments to allow removal of SYSTEM_USER role

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
This endpoint is called by 7 clients
No changes are required for the following:
create-and-vary-a-licence-admin - does not have SYSTEM_USER role
keyworker-api - has VIEW_PRISONER_DATA role
manage-key-workers - does not have SYSTEM_USER role
prison-staff-hub - does not have SYSTEM_USER role
visits-orchestration-service- has VIEW_PRISONER_DATA role
Changes required for clients - NEEDS VIEW_PRISONER_DATA role : 
manage-prison-visits-client
offender-risk-profiler
> SDIT-1120 Remove deprecated SYSTEM_USER role in favour of existing VIEW_PRISONER_DATA when viewing booking summary

- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
Removing the SYSTEM_USER role means all clients calling this endpoint with the SYSTEM_USER role now require the INACTIVE_BOOKINGS role.
Those not requiring change (Do not currently have SYSTEM_USER role):
book-video-link-client
create-and-vary-a-licence-admin
prison-staff-hub
licences-cloudplatform
manage-key-workers
Those requiring role to be added:
categorisation-tool
licencesadmin-cloud-platform
manage-pom-cases-api
> SDIT-1120 Only allow inactive bookings for clients with INACTIVE_BOOKINGS role

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/BookingResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest_getCalculableSentenceEnvelope.kt
This is the second way a bulk calculate release dates comparison happens. This is modelled the same as https://github.com/ministryofjustice/prison-api/blob/main/src/main/java/uk/gov/justice/hmpps/prison/api/resource/PrisonResource.kt#L47 but retrieving active bookings by a set of offender numbers instead of establishment id
> CRS-1500 added get calculable sentence envelope by offender nos

- src/main/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/ReleasePrisonerService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderResourceIntTest_release.kt
Turns out we [have lots of calls failing on T3](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fc27cfedb-f5e9-45e6-9642-0fad1a5c94e7%2FresourceGroups%2Fnomisapi-t3-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-t3/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAytKLSxNLS4p5qpRKM9ILUpVSM7JL02JD8rPSfVLzE1VsLVVUC8oyizOz9NNLMhUhyvLg0oqBYSGKOgDpfTz09JS81JSi4r1q2FMv%252Fxa%252FaLUnNTE4lQlAI%252B6CzJpAAAA/timespan/P1D) because they don't send comments in the request.
> SDIT-548 Allow for missing comments

- src/main/java/uk/gov/justice/hmpps/prison/service/StaffService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/StaffResourceIntTest.kt
Added STAFF_SEARCH to 
1. **manage-pom-cases-api** 
2. **offender-management-allocation-manager**
3. **welcome-people-into-prison-client** 
**keyworker-api** already had the role
**manage-key-workers** did not have SYSTEM_USER (so did not need the alternative role)
> SDIT-1268 Remove SYSTEM_USER access from GET /api/staff/roles/{agencyId}/role/{role}

- src/main/java/uk/gov/justice/hmpps/prison/service/GlobalSearchService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonerResourceTest.kt
All associated clients either have both SYSTEM_USER and VIEW_PRISONER_DATA or do not have SYSTEM_USER - SYSTEM_USER can therefore be removed from the endpoint
> SDIT-1281 Remove SYSTEM_USER from GET /api/prisoners/{offenderNo}

- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest.kt
Updated clients to also have VIEW_SCHEDULES role:
book-a-secure-move-api (Prod/Preprod/dev)
book-a-secure-move-api-uat (dev)
serco-book-a-secure-move (dev)
> SDIT-1288 Remove SYSTEM_USER from activies and properties endpoints

- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToUpdateOffenderDates.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
Allows the reason for calculation in NOMIS to be updated with a reason selected by the CRDS user.
> CRS-1779: Update NOMIS key dates with reason

- src/main/java/uk/gov/justice/hmpps/prison/api/model/AssessmentDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderAssessmentServiceTest.kt
- src/test/resources/uk/gov/justice/hmpps/prison/api/resource/impl/csra_assessment.json
On the new prisoner profile CSRA pages we're looking to include more information which is currently available in NOMIS but not available in DPS for viewing - these fields are the ones added in this PR. 
Some of these fields are conditionally returned already
- the classification codes are returned via the existing `classificationCode` field
- the override reason/approval comment both get returned via `classificationReviewReason`
However as it already has internal logic in the API we were unable to display all of the fields to the user at once if required for a better understanding. Rather than update the logic in those fields (which may be used/depended on elsewhere) i opted to add new fields instead.
> CDPS-607: Add more data to CSRA assessment endpoint

- src/main/java/uk/gov/justice/hmpps/prison/api/model/Movement.java
From agency can be null, swagger docs indicated it was non-null. This should update the swagger docs to make it clear that the field can be null.
> Updated annotations for from agency

- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/AgencyResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderSentenceResourceImplIntTest.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonerResourceTest.kt
This affects the following endpoints:
- GET /api/offender-sentences
- POST /api/offender-sentences
- POST /api/offender-sentences/bookings
- GET /api/prisoners/{offenderNo}/full-status
> SDIT_1496 Remove SYSTEM_USER from BookingService.isViewInactiveBookings

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocation.java
- src/main/java/uk/gov/justice/hmpps/prison/service/AgencyService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/MovementUpdateService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/BookingIntoPrisonService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/TransferIntoPrisonService.kt
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/AgencyInternalLocationTest.java
This commit removes the boolean parameter 'treatZeroOperationalCapacityAsNull' from the capacity check methods in AgencyInternalLocation class. Now the methods consider operational capacity as zero when it is null. The related tests and class methods that use those methods have also been updated accordingly.
> MAP-494 Refactor capacity check methods in AgencyInternalLocation

- build.gradle.kts
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingId.kt
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/OffenderBookingRepositoryTest.kt
The original queries had two issues:
1. They were meant to return offender bookings, but these would sometimes be duplicated (if multiple sentences exist) as the query was eager fetching with a left outer join.  See https://developer.jboss.org/docs/DOC-15782#jive_content_id_Hibernate_does_not_return_distinct_results_for_a_query_with_outer_join_fetching_enabled_for_a_collection_even_if_I_use_the_distinct_keyword for more information
2. Pagination was specified with eager fetching.  This means that hibernate had to load the whole prison data into memory before then doing the paging.  See https://stackoverflow.com/questions/11431670/how-can-i-avoid-the-warning-firstresult-maxresults-specified-with-collection-fe
> SDIT-1579: 🐛 Fix sentence query and upgrade hibernate

- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderCalculatedKeyDates.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderKeyDates.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderDatesResource.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
Docs were pointing at the wrong types on 2 of the offender key dates endpoints. Added calculation timestamp to get offender key dates.
> CRD-1849: fix docs and add latest calc timestamp to key offender dates

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderAssessment.java
- src/test/java/uk/gov/justice/hmpps/prison/repository/jpa/model/OffenderAssessmentTest.java
Following advice from security collegues the way the CSRA asessement is displayed has been changed. Instead of overrides returning a blank CSRA rating until approved - it now displays the higher of the two in case of it being HI until approved, at which point it will display the final result.
> CDPS-690: Update CSRA Override behaviour

- src/main/java/uk/gov/justice/hmpps/prison/api/model/PrisonerSearchDetails.kt
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/PrisonerSearchResource.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/BookingService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerSearchService.kt
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/PrisonerSearchResourceIntTest.kt
This is the first PR in a multi-stage plan to switch to a new endpoint deicated to prisoner search.
- first we've created an endpoint that only includes details required by prisoner search
- for now this is calling the old InmateService to get data, and testing against the same old seed data
- we will then create a test fixture in prisoner search to compare the old and new endpoints with production data to give us confidence that the new endpoint works the same as the old one
- once established we can switch prisoner search to the new endpoint
- we will then be able to add additional data to the new endpoint without affecting other prison-api clients
- then we'll rewrite the tests for the new endpoint such that we don't rely on the seed data
- once we're happy with the test coverage we …
> SDIT-1617 New endpoint dedicated to prisoner search

- src/main/java/uk/gov/justice/hmpps/prison/api/model/InmateDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenceHistoryDetail.java
- src/main/java/uk/gov/justice/hmpps/prison/service/InmateService.java
- src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerSearchService.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/transformers/OffenderTransformer.java
- src/test/java/uk/gov/justice/hmpps/prison/service/enteringandleaving/TransferIntoPrisonServiceTest.kt
This is for the new prisoner search endpoint that's not being used **yet** - it's being tested in parallel with the old endpoint to make sure it provides the same details. We don't want to get this wrong so we're testing with real data.
The idea is to move the endpoint away from InmateService (which relies heavily on SQL based repositories) and onto JPA instead. We haven't achieved this yet but this but are now using JPA modelling where it exists (still more to do).
> SDIT-1617 Start moving towards JPA instead of InmateService

- src/main/java/uk/gov/justice/hmpps/prison/repository/InmateAlertRepository.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/BookingResourceIntTest.kt
When an alert is created, and it has already expired the status should be set to INACTIVE
> SDIT-1755 Fix issue where expired new alerts are created active

- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderDatesResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
This now ignores the current booking as it was producing undesirable results.
> CRS-1852 Tweak the TUSED retrieval method.

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/AgencyResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/CellResource.java
- src/main/java/uk/gov/justice/hmpps/prison/api/resource/LocationResource.java
Marked several methods in the AgencyResource, LocationResource, and CellResource classes as deprecated. The Location service will provide this data in the future.
Methods shown [here](https://docs.google.com/spreadsheets/d/1xa0MJNMreQcqONtS9alkF_5Hg3NvWSCckDIyr2KQOXA/edit?usp=sharing)
> MAP-1357-deprecate-endpoints-in-prison-api-and-whereabouts-api

- src/main/java/uk/gov/justice/hmpps/prison/repository/sql/ScheduleRepositorySql.kt
- src/test/java/uk/gov/justice/hmpps/prison/repository/ScheduleRepositoryTest.java
The BLVS service needs to be able to make amendments to appointments in NOMIS.
To do this we need the appointment event ID (which we don't store in our service).  To achieve this we have to search for appointments based on criteria we do hold e.g. prison code, prisoner number, date, etc.
> BAVL-213 adds the event id to the response object on the schedules appointment search endpoint so appointments can be explicitly identified.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
`internal` looks to be deprecated anyway now - see https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml#L26.
Suggestion is
>     internal: # Deprecated, use digital_staff_and_mojo or moj_cloud_platform or both, as appropriate for your service
which is what I've implemented.
> SDIT-2264: ✨ Add mojo allowlist for dev and pre-prod

- src/main/java/uk/gov/justice/hmpps/prison/api/resource/OffenderDatesResource.java
- src/main/java/uk/gov/justice/hmpps/prison/repository/jpa/repository/OffenderBookingRepository.java
- src/main/java/uk/gov/justice/hmpps/prison/service/OffenderDatesService.java
- src/test/java/uk/gov/justice/hmpps/prison/api/resource/impl/OffenderDatesResourceTest.java
- src/test/java/uk/gov/justice/hmpps/prison/service/OffenderDatesServiceTest.java
this functionality is only used by the calculate-release-dates service
> CRS-2224 Change method that retrieves latest TUSED calculated date to be booking agnostic (previously it ignored the latest booking)

- src/main/java/uk/gov/justice/hmpps/prison/api/model/AddressDto.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/OffenderRestriction.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/RequestToUpdateAddress.java
- src/main/java/uk/gov/justice/hmpps/prison/api/model/v1/CreateTransaction.java
Due to a change in the last few months, the API schema is producing a new output. We noticed this because it is impacting the mock produced by Prism. I've made a few changes to produce a cleaner mock including:
- Fixing booleans
- Splitting a list of allowed values as a string into a list of strings
- Introducing examples for some fields
> Fix API Schema

- src/main/java/uk/gov/justice/hmpps/prison/api/model/imprisonmentstatus/ImprisonmentStatusHistoryDto.kt
- src/main/java/uk/gov/justice/hmpps/prison/service/imprisonmentstatus/ImprisonmentStatusHistoryService.kt
- src/test/java/uk/gov/justice/hmpps/prison/service/imprisonmentstatus/ImprisonmentStatusHistoryServiceTest.kt
Add bookingId and bookNumber to /api/imprisonment-status-history/{offenderNo}. This allows the identify remand tool to tell users where to go to fix issues with recall or remand imprisonment status changes, e.g. missing court events.
> ADJST-996: Add booking ids to imprisonment status
